### ISSUE TITLE
Handling parameter for basecommand

### ISSUE THREAD

**Issue by manabuishii** [tom-tan/zatsu-cwl-generator#4]
./zatsu_cwl_generator.d "head -n 5 ccc.txt > output.txt"

`-n` needs `- `( dash,space) .

Actual

```cwl
./zatsu_cwl_generator.d "head -n 5 ccc.txt > output.txt"
class: CommandLineTool
cwlVersion: v1.0
baseCommand: head
arguments:
-n
  - $(inputs.5)
  - $(inputs.ccc_txt)
inputs:
  - id: 5
    type: int
  - id: ccc_txt
    type: File
outputs:
  - id: out
    type: stdout
stdout: output.txt
```

Expected

```
./zatsu_cwl_generator.d "head -n 5 ccc.txt > output.txt"
class: CommandLineTool
cwlVersion: v1.0
baseCommand: head
arguments:
  - -n
  - $(inputs.5)
  - $(inputs.ccc_txt)
inputs:
  - id: 5
    type: int
  - id: ccc_txt
    type: File
outputs:
  - id: out
    type: stdout
stdout: output.txt
```
